### ISSUE TITLE
Use icon button for "New game"

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Haiku2048#10]
If #9 "undo button" is going to be implemented, change the "New game" button to an icon button with tool tip as well.

**Comment by dospuntos** [comment]
@humdingerb I believe this has been implemented already?

**Comment by humdingerb** [comment]
Indeed. Though a tool tip would be nice. As it's a destructive action, it'd also be cool to have the undo button restore the old game state. A new ticket mayhaps...
