### ISSUE TITLE
Improve score and highscore display

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Haiku2048#20]
Beside using icon buttons - see #10 - it'd be nice to make the display of the highscore and score nicer. Suggestion:

![2048_mockup](https://user-images.githubusercontent.com/6107158/34320862-cdf6c07e-e802-11e7-8009-b36dd195e14d.png)

**Comment by luka177** [comment]
Id like to do this

**Comment by luka177** [comment]
Hmm it looks so in readme

**Comment by humdingerb** [comment]
Indeed. Done with 7279a7ba92ba45cd50e8c6520b1e26b185ab4461
