### ISSUE TITLE
Enter highscore name in a floating window

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Haiku2048#21]
When it's time to enter the highscore, a new floating window should be opened to enter the user name. It should also be more festive, saying something like:
___________________________
# Congratulations!
You achieved a new highscore, beating the one
by {Here-the-old-leader} by {new-highscore - old-highscore}.

Your new highscore is:
### {new-highscore}

Please enter your name:
___________________________

**Comment by R4H33M** [comment]
I'd like to take this.

**Comment by harshit-sharma-gits** [comment]
Hey @humdingerb, I open up a PR for this issue. Please take a look.

**Comment by dospuntos** [comment]
I believe this issue has been solved and may be closed?

**Comment by humdingerb** [comment]
Yep. Fixed with 65875288d466bb0e85d83dfe3ac212745cb9c6e0
Thanks!
