### ISSUE TITLE
Floating board to enter hiscore has a fixed gray colour

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/Haiku2048#31]
The problem is that the colour of text "Enter your name" follow user colour scheme (panel_text_colour) but that panel is of a fixed gray colour. In a dark scheme, this text colour will be light making the text difficult to read.

Either, use fixed colours for this panel text and background (fixing the text colour to black and dark gray would do it)
or follow user colour scheme for both panel and text colours (this would make more sense as the text box is already following it).

**Comment by humdingerb** [comment]
Just to clarify, you mean this _blue_ colour background at the bottom?

![screenshot1](https://user-images.githubusercontent.com/6107158/187065222-cb9719b6-7e52-4b17-9bed-0fcb01793ce3.png)

**Comment by Briseur** [comment]
Yes, this one indeed.
