### ISSUE TITLE
Resizing window should resize tiles

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Haiku2048#7]
Resizing the window should resize the tiles together with the tile number. The aspect ratio should stay the same.

**Comment by bach5000** [comment]
Also working on it :)

**Comment by janus2** [comment]
Regression?
![resizing](https://user-images.githubusercontent.com/10423645/34460581-f47b7a94-ee12-11e7-9d72-fd22c411d90c.png)

**Comment by ondralukes** [comment]
Working on it
