### ISSUE TITLE
Thread "TerminalBoard control keeper" is pegging

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Haiku2048#8]
Not sure it was always the case, but right from the start the thread "TerminalBoard control keeper" is pegging a CPU core.

**Comment by mmuman** [comment]
Ah, actually only when you run from Tracker or with `open`, probably because it sets `stdin` to `/dev/null`.

**Comment by mmuman** [comment]
At least removing the terminal code fixes it.
